// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgoYx8uh7W9Zojxouuuywdo5-C6rYOkuU',
    appId: '1:653991261533:web:3adaca64fee84dbaa024b4',
    messagingSenderId: '653991261533',
    projectId: 'cozinhafacil-6bafd',
    authDomain: 'cozinhafacil-6bafd.firebaseapp.com',
    databaseURL: 'https://cozinhafacil-6bafd-default-rtdb.firebaseio.com',
    storageBucket: 'cozinhafacil-6bafd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2GDvBjsZTTDWK3dDtvZAvDE6hOCsuaMA',
    appId: '1:653991261533:android:5ed7a7797d11d280a024b4',
    messagingSenderId: '653991261533',
    projectId: 'cozinhafacil-6bafd',
    databaseURL: 'https://cozinhafacil-6bafd-default-rtdb.firebaseio.com',
    storageBucket: 'cozinhafacil-6bafd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB98jLzw5pQxvJLZd1UvUgUZtJy2mWGqgg',
    appId: '1:653991261533:ios:8b7bf9f1ca7978d4a024b4',
    messagingSenderId: '653991261533',
    projectId: 'cozinhafacil-6bafd',
    databaseURL: 'https://cozinhafacil-6bafd-default-rtdb.firebaseio.com',
    storageBucket: 'cozinhafacil-6bafd.appspot.com',
    iosBundleId: 'com.example.cozinhafacil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB98jLzw5pQxvJLZd1UvUgUZtJy2mWGqgg',
    appId: '1:653991261533:ios:9556754a183f947ba024b4',
    messagingSenderId: '653991261533',
    projectId: 'cozinhafacil-6bafd',
    databaseURL: 'https://cozinhafacil-6bafd-default-rtdb.firebaseio.com',
    storageBucket: 'cozinhafacil-6bafd.appspot.com',
    iosBundleId: 'com.example.cozinhafacil.RunnerTests',
  );
}
